server:
  port: 8080

spring:
  application:
    name: common-service
  config:
    import: "nacos:global-config.yml"
  cloud:
    openfeign:
      httpclient:
        enabled: true
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 3000
          user-service:
            logger-level: full
            connect-timeout: 2000
            read-timeout: 2000