server:
  port: 11453
spring:
  application:
    name: video-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  config:
    import: "nacos:global-config.yml,nacos:video-service.yml,nacos:database-config.yml"
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            namespace: ""
            group-id: SENTINEL_RULES
            data-id: video-service-flow-rules
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: localhost:8848
            namespace: ""
            group-id: SENTINEL_RULES
            data-id: video-service-degrade-rules
            data-type: json
            rule-type: degrade
    nacos:
      discovery:
        server-addr: localhost:8848
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        videoEvent-out-0:
          destination: video-events
          content-type: application/json
        videoEventConsumer-in-0:
          destination: video-events
          group: video-search-consumer
          content-type: application/json
      function:
        definition: videoEventConsumer
  elasticsearch:
    uris: http://localhost:9200
feign:
  sentinel:
    enabled: true
seata:
  application-id: seata-service-business
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: ""
      group: SEATA_GROUP
      application: seata-server #Nacos 中 Seata 名称
      username: nacos
      password: nacos
  tx-service-group: seata_tx_group #事务组（被一个集群管理）
  service:
    vgroup-mapping:
      seata_tx_group: default
  data-source-proxy-mode: AT #运行模式
  enable-auto-data-source-proxy: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'video-service'
      paths-to-match: '/**'
      packages-to-scan: com.hiiro.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
#视频上传缓存位置
video:
  upload:
    tmp: hirihiri-backend/tmp/uploads